#!/bin/bash

echo "🧪 12月13日 八潮北公園 庭球場E の「取」マーク検知テスト"
echo "============================================================"
echo ""
echo "📋 テスト対象:"
echo "  施設: 八潮北公園 庭球場E (ID: 10300050)"
echo "  日付: 2025-12-13 (土曜日)"
echo "  時間: 11:00~ (スクリーンショットで「取」マーク確認済み)"
echo ""
echo "🔍 検証項目:"
echo "  1. 週間カレンダーから正しくデータを取得できるか"
echo "  2. 「取」マーク (mark_tori.gif) を検出できるか"
echo "  3. 申込人数を正しくパースできるか"
echo "  4. status='applicants' が設定されるか"
echo ""
echo "============================================================"
echo ""
echo "💡 手動確認手順:"
echo ""
echo "1. 品川区予約システムにアクセス:"
echo "   https://cm9.eprs.jp/shinagawa/web/rsv"
echo ""
echo "2. ログイン情報を入力してログイン"
echo ""
echo "3. 「予約」→「週間表示」を選択"
echo ""
echo "4. 施設選択で「八潮北公園 庭球場E」を選択"
echo ""
echo "5. カレンダーで12月13日(土)を表示"
echo ""
echo "6. 11:00~の枠を確認:"
echo "   - 「取」マークが表示されているか"
echo "   - 申込人数が表示されているか"
echo ""
echo "============================================================"
echo ""
echo "🔧 コード実装の確認:"
echo ""
echo "検知ロジック (workers/src/scraper.ts):"
echo ""
echo "```typescript"
echo "// 「取」マークの検出"
echo "if (imgSrc.includes('mark_tori.gif')) {"
echo "  status = 'applicants';"
echo "  "
echo "  // 申込人数の抽出"
echo "  const applicantMatch = cellText.match(/取\\((\\d+)名\\)/);"
echo "  if (applicantMatch) {"
echo "    applicantCount = parseInt(applicantMatch[1], 10);"
echo "  }"
echo "}"
echo "```"
echo ""
echo "============================================================"
echo ""
echo "✅ 確認済み実装:"
echo "  - ✅ 「取」マーク画像 (mark_tori.gif) の検出"
echo "  - ✅ applicantCount のパース (正規表現)"
echo "  - ✅ status='applicants' の設定"
echo "  - ✅ Push通知での「取」マーク通知対応"
echo ""
echo "🎯 期待される動作:"
echo "  - 11:00~の枠が status='applicants' で返される"
echo "  - applicantCount に実際の申込人数が入る"
echo "  - 監視中の場合、Push通知が送信される"
echo ""
echo "============================================================"
