#!/bin/bash

echo "==================================================="
echo "🧪 集中監視テスト手順書"
echo "==================================================="
echo ""

echo "📝 テスト手順:"
echo "---------------------------------------------------"
echo ""
echo "【方法1: 実環境でのテスト】"
echo "1. PWAで品川区の監視設定を追加"
echo "   - 施設: 任意の施設"
echo "   - 日付: 近い将来の日付"
echo "   - 時間帯: 1つ選択"
echo ""
echo "2. 品川区サイトで手動で「取」マークにする"
echo "   - ログイン後、該当の日時を「取」予約"
echo ""
echo "3. 次のCron実行（1分以内）を待つ"
echo ""
echo "4. 以下のコマンドで確認:"
echo "   ./check-intensive.sh"
echo ""
echo ""
echo "【方法2: ログ監視】"
echo "リアルタイムでログを監視:"
echo ""
echo "  cd workers"
echo "  npx wrangler tail --format pretty | grep -E 'IntensiveCheck|取.*検知|集中監視'"
echo ""
echo ""
echo "【期待される動作】"
echo "---------------------------------------------------"
echo "1. 「取」検知時:"
echo "   [Alert] 🔥「取」検知: 2025-xx-xx xx:xx-xx:xx - 集中監視モード開始"
echo "   [Alert] 次回監視: xx:x0:00 (10分単位)"
echo ""
echo "2. 次の10分単位の前後15秒に:"
echo "   [IntensiveCheck] 🔥 集中監視モード実行中: ..."
echo "   [IntensiveCheck] チェック 1/30 実行中..."
echo "   [IntensiveCheck] チェック 2/30 実行中..."
echo "   ..."
echo ""
echo "3. 「○」検知時:"
echo "   [IntensiveCheck] 🎉 「取」→「○」検知！即座に予約実行"
echo "   → 通常監視に復帰"
echo ""
echo "4. 「×」検知時:"
echo "   [IntensiveCheck] ❌ 「取」→「×」に変化、集中監視終了"
echo "   → 通常監視に復帰"
echo ""
echo "5. 予約日時到達時:"
echo "   [IntensiveCheck] ⏰ 予約日時到達、集中監視終了"
echo "   → 通常監視に復帰"
echo ""
echo "==================================================="
